# Basic
title: Jim Leung
subtitle: Personal Site
description: Welcome to my personal site~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Jim Leung
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Linux/ComputerVisoin
url: "http://jimleungjing.github.io"

# Comment
comment:
    disqus: jimleung
    # uyan: 2158321  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    weibo: 15996253992
    github: jimleung
    # twitter: 
    mail: yusnowsliang@gmail.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
#baidu:
#    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
#ga:
#    id: UA-84134159-3   
#    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    {title: blogs, description: blogs, url: '/about'}

# Navigation buttons in the front page.s
nav:
    - {title: archives, description: archive, url: 'https://jimleungjing.github.io/archives/'}
    - {title: github, description: github, url: 'https://github.com/jimleungjing'}   
    - {title: aboutme, description: about, url: '/about'}
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


